<a href="https://colab.research.google.com/github/Chaitanya2ca/TNS_Training_AIML/blob/main/Kaggle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle (1).json

{'kaggle (1).json': b'{"username":"gchaitanyakumarreddy","key":"56e9378db39a3ec9aaaf07ff8616953a"}'}

In [6]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [7]:
!pip install -q kaggle

In [8]:
!kaggle datasets list

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                                              title                                                    size  lastUpdated                 downloadCount  voteCount  usabilityRating
---------------------------------------------------------------  -------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
dmitriigluzdov/casmi26-pubchem-popularity-prior                  CASMI26 PubChem Popularity Prior                   1286771429  2026-10-05 02:40:35.677000           4371         35                1
srisyra02/zomato-market-analysis                                 Restaurant Market Analysis: Ratings, Prices            444049  2026-09-17 17:02:06.437000           4541         94                1
dreaddevelopment/raptor-knee-maxspan                             Knee MRI - Max-Span Dense Corpus                    271659195  2026-08-22 20:14:47.093000           1622         50           0.8125
dreaddevelopment/raptor-knee-native384dense                      Knee MRI - Native 384 Dense Corpus                  271657808  2026-08-23 13:17:23.333000            805         25           0.8125
dreaddevelopment/raptor-knee-native384                           Knee MRI - Native 384 Corpus                        271660739  2026-08-23 00:35:34.303000            730         25           0.8125
ahmedberatozer/casmi26-glacier                                   casmi26-glacier                                      56264835  2026-09-28 09:32:41.470000           4730         21            0.625
anvithpothula/biohub-v1284-head-s075                             biohub v1284 head s075                                  30104  2026-09-20 14:13:26.057000           1035         35            0.875
harishyadav0506/impact-of-social-media-on-life                   Impact of Social Media on Life                          78980  2026-09-09 18:10:54.497000           5226         89                1
samartalwar/sleep-debt-and-screen-time-late-night-phone-habits   Sleep Debt & Screen Time: Late Night Phone Habits      210821  2026-09-21 11:50:10.110000           3361         64                1
ahmedberatozer/casmi26-fpnet-full1                               casmi26-fpnet-full1                                 184261486  2026-09-29 10:10:49.307000            512         10            0.625
datascikhan/e-commerce-sales-and-customer-analytics              E-Commerce Sales Analytics Dataset                   29815424  2026-08-25 08:00:46.013000          17040        341                1
ahmedberatozer/casmi26-v3-models                                 casmi26-v3-models                                   374959744  2026-09-23 10:45:15.137000           2052          4            0.625
eishatuzzuhra/ai-usage-and-impact-on-students-and-professionals  AI Usage and Impact on Students & Professionals         20123  2026-09-28 12:38:54.317000           1352         50                1
dmitriigluzdov/casmi26-natural-product-panel-benchmark           CASMI26 Natural-Product Panel Benchmark              55519487  2026-09-30 11:12:26.460000           1004         23                1
prvsiyan/casmi26-fp-models-v2                                    CASMI26 fingerprint models (single + merged)        267281678  2026-09-16 22:50:48.873000           2801          6           0.4375
datascikhan/supermarket                                          Supermarket 🏪                                        62837823  2026-09-24 06:33:48.830000            666         22                1
datascikhan/cars-dataset                                         Cars Dataset 🚗                                       74910525  2026-09-24 06:28:58.163000            472         26                1
ahmedberatozer/casmi26-v2-pool                                   casmi26-v2-pool                                     704631733  2026-09-21 08:18:58.990000           1305          2       0.47058824
srisyra02/online-food-ordering-dataset                           Online Food Ordering Dataset                             3648  2026-08-23 15:26:25.483000          12118        192                1
zeyadmohamed26/netflix-customer-churn-and-engagement-analytics   Netflix Customer Churn & Engagement Analytics          190004  2026-09-07 11:24:25.160000           2981         48                1

In [9]:
!kaggle datasets list -s cars-dataset

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                             title                                     size  lastUpdated                 downloadCount  voteCount  usabilityRating
----------------------------------------------  ----------------------------------  ----------  --------------------------  -------------  ---------  ---------------
austinreese/craigslist-carstrucks-data          Used Cars Dataset                    275237598  2021-05-06 17:14:08.443000         121796       1686                1
doaaalsenani/usa-cers-dataset                   US Cars Dataset                          67478  2020-04-22 14:38:05.453000          44764        425                1
ayushparwal2026/cars-dataset                    Cars Dataset                            173037  2024-03-11 16:23:49.663000          10192         92                1
tr1gg3rtrash/cars-2022-dataset                  Cars 2022 Dataset                         6357  2022-09-03 08:40:38.460000           8683        118                1
ander289386/cars-germany                        Germany Cars Dataset                    509754  2021-06-09 16:14:27.943000           7371         65                1
gabrielsantello/cars-purchase-decision-dataset  Cars - Purchase Decision Dataset          6280  2022-07-09 13:18:38.727000          20865        129                1
mrmars1010/cars-india-pre-owned                 Used Cars Dataset                        73861  2024-09-29 01:19:49.630000           3339         60                1
iamsouravbanerjee/cars-dataset                  Cars Dataset                            584557  2023-10-17 05:58:29.647000           5252         66                1
abdulmalik1518/cars-datasets-2025               Cars Datasets (2025)                     25987  2025-07-17 21:43:28.493000          35046        426                1
ananaymital/us-used-cars-dataset                US Used cars dataset                2287140843  2020-09-21 04:49:21.140000          10044         97                1
mahmoudahmed6/yallamotors-cars-dataset          Cars Dataset                            113542  2021-12-12 10:44:33.017000           1059         42                1
ayazlakho/carsdataset                           cars-dataset                            100359  2022-08-02 06:26:06.357000           1575         29                1
abdullahkhanuet22/olx-cars-dataset              Cars Dataset                           1801273  2024-01-14 10:22:23.087000           3007         34                1
midhundasl/co2-emission-of-cars-dataset         CO2 emission of cars dataset           6933392  2026-01-15 07:23:23.570000           7098         92        0.9411765
eduardo4jesus/stanford-cars-dataset             Stanford Cars Dataset               1959400431  2019-02-21 18:00:43.010000          13343         67            0.625
shivanink8/used-cars-dataset                    Used Cars Dataset                         2843  2023-02-24 00:02:29.517000           3038         34                1
whenamancodes/automobiles-project-dataset       Automobiles | Cars Project Dataset        6602  2023-07-08 17:08:45.287000           3341         44                1
waqi786/cars-dataset-2010-2020                  Cars Dataset (2010-2020)                 98742  2024-07-23 05:49:46.990000           3362         37                1
makslypko/cars-dataset                          Cars Dataset🚘                            46947  2024-10-16 11:19:31.387000           1714         33                1
boulahchichenadir/algerian-used-cars            cars classification dataset           54074974  2022-04-16 11:11:02.447000           1951         29                1

In [10]:
!kaggle datasets download -d datascikhan/cars-dataset

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/datascikhan/cars-dataset
License(s): CC0-1.0
Downloading cars-dataset.zip to /content
100% 71.4M/71.4M [00:00<00:00, 128MB/s]

In [11]:
!unzip -o cars-dataset.zip

Archive:  cars-dataset.zip
  inflating: cars_dataset.csv

In [17]:
import pandas as pd
df=pd.read_csv("cars_dataset.csv")

In [18]:
df.head()

,vehicle_id,listing_id,seller_id,dealer_id,make,model,model_variant,model_year,vehicle_year,vehicle_age,...,description_quality_score,vehicle_presentation_score,image_quality_score,listing_completeness_score,vehicle_risk_score,mechanical_risk_score,accident_risk_score,maintenance_risk_score,depreciation_risk_score,resale_risk_score
0,V00000001,L00000001,S00000001,NaN,BMW,i4,i4 RS,2020,2020,6,...,41.7,46.4,45.2,46.6,32.3,40.2,NaN,69.2,32.5,69.8
1,V00000002,L00000002,S00000002,D00000002,Chevrolet,Equinox,Equinox SE,2016,2016,10,...,35.5,46.6,44.0,67.9,49.8,63.6,36.2,100.0,NaN,26.4
2,V00000003,L00000003,S00000003,D00000003,Kia,Sportage,Sportage M Sport,2024,2024,2,...,53.5,58.2,62.8,78.5,33.3,0.6,12.3,NaN,51.4,6.6
3,V00000004,L00000004,S00000004,NaN,Hyundai,Ioniq 5,Ioniq 5 Sport,2015,2015,11,...,46.2,59.5,40.7,51.2,29.8,29.5,24.5,100.0,100.0,26.9
4,V00000005,L00000005,S00000005,D00000005,Honda,Accord,Accord GT,2022,2022,4,...,23.1,42.5,17.4,78.0,22.5,0.0,10.4,74.7,74.6,36.4

In [21]:
df.tail()

,vehicle_id,listing_id,seller_id,dealer_id,make,model,model_variant,model_year,vehicle_year,vehicle_age,...,description_quality_score,vehicle_presentation_score,image_quality_score,listing_completeness_score,vehicle_risk_score,mechanical_risk_score,accident_risk_score,maintenance_risk_score,depreciation_risk_score,resale_risk_score
99995,V00099996,L00099996,S00004996,D00001996,Volkswagen,Jetta,Jetta SEL,2020,2020,6,...,19.4,39.4,58.9,66.5,41.2,22.8,15.3,79.3,65.3,37.9
99996,V00099997,L00099997,S00004997,NaN,Ford,Transit,Transit Premium,2026,2026,0,...,40.3,64.6,40.6,65.1,37.7,2.5,1.9,23.6,29.9,51.5
99997,V00099998,L00099998,S00004998,D00001998,Chevrolet,Traverse,Traverse Limited,2026,2026,0,...,35.7,48.2,33.4,67.3,35.1,17.4,5.3,1.3,10.1,37.6
99998,V00099999,L00099999,S00004999,D00001999,Mazda,Mazda6,Mazda6 Base,2023,2023,3,...,27.6,45.6,44.0,74.9,18.5,20.0,13.3,33.0,45.8,36.8
99999,V00100000,L00100000,S00005000,NaN,Hyundai,Ioniq,Ioniq M Sport,2020,2020,6,...,57.0,60.4,79.8,56.3,39.1,25.4,0.0,56.4,74.4,24.6

In [19]:
df.size

43700000

In [20]:
df.shape

(100000, 437)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Columns: 437 entries, vehicle_id to resale_risk_score
dtypes: bool(4), float64(207), int64(133), object(93)
memory usage: 330.7+ MB

In [24]:
df.describe()

,model_year,vehicle_year,vehicle_age,brand_reputation_score,brand_reliability_score,brand_premium_index,brand_market_share,manufacturer_warranty_years,manufacturer_warranty_km,engine_displacement_cc,...,description_quality_score,vehicle_presentation_score,image_quality_score,listing_completeness_score,vehicle_risk_score,mechanical_risk_score,accident_risk_score,maintenance_risk_score,depreciation_risk_score,resale_risk_score
count,100000.00000,100000.00000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,...,97000.000000,97000.000000,97000.000000,97000.000000,100000.000000,97000.000000,97000.000000,96000.000000,97000.000000,97000.000000
mean,2020.61357,2020.61357,5.38643,85.720630,84.331600,48.024440,8.473608,4.07430,81486.000000,2441.182000,...,50.138122,59.049049,44.022342,59.925245,35.129561,26.482953,11.749782,61.030784,58.356208,29.586944
std,4.07702,4.07702,4.07702,4.545084,6.620944,18.217876,2.821606,0.87051,17410.193427,1291.038772,...,19.545534,11.288012,16.362670,14.998831,13.738588,13.861467,12.571660,33.765959,30.002967,16.071916
min,2011.00000,2011.00000,0.00000,78.000000,76.000000,32.000000,3.500000,3.00000,60000.000000,0.000000,...,10.000000,17.000000,5.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2018.00000,2018.00000,2.00000,82.000000,78.000000,38.000000,6.500000,3.00000,60000.000000,1600.000000,...,36.400000,51.300000,32.800000,49.900000,25.800000,16.500000,0.600000,29.700000,36.500000,18.000000
50%,2021.00000,2021.00000,5.00000,85.000000,82.000000,40.000000,8.000000,4.00000,80000.000000,2300.000000,...,50.000000,58.900000,44.000000,60.000000,35.100000,26.100000,8.600000,61.400000,63.000000,29.300000
75%,2024.00000,2024.00000,8.00000,90.000000,92.000000,50.000000,11.800000,5.00000,100000.000000,3500.000000,...,63.600000,66.700000,55.100000,70.100000,44.400000,35.900000,17.900000,100.000000,83.800000,40.600000
max,2026.00000,2026.00000,15.00000,93.000000,95.000000,90.000000,12.500000,5.00000,100000.000000,6200.000000,...,100.000000,100.000000,100.000000,100.000000,93.500000,82.700000,94.700000,100.000000,100.000000,100.000000

In [31]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Length: 100000, dtype: bool

In [32]:
df.drop_duplicates()

,vehicle_id,listing_id,seller_id,dealer_id,make,model,model_variant,model_year,vehicle_year,vehicle_age,...,description_quality_score,vehicle_presentation_score,image_quality_score,listing_completeness_score,vehicle_risk_score,mechanical_risk_score,accident_risk_score,maintenance_risk_score,depreciation_risk_score,resale_risk_score
0,V00000001,L00000001,S00000001,NaN,BMW,i4,i4 RS,2020,2020,6,...,41.7,46.4,45.2,46.6,32.3,40.2,NaN,69.2,32.5,69.8
1,V00000002,L00000002,S00000002,D00000002,Chevrolet,Equinox,Equinox SE,2016,2016,10,...,35.5,46.6,44.0,67.9,49.8,63.6,36.2,100.0,NaN,26.4
2,V00000003,L00000003,S00000003,D00000003,Kia,Sportage,Sportage M Sport,2024,2024,2,...,53.5,58.2,62.8,78.5,33.3,0.6,12.3,NaN,51.4,6.6
3,V00000004,L00000004,S00000004,NaN,Hyundai,Ioniq 5,Ioniq 5 Sport,2015,2015,11,...,46.2,59.5,40.7,51.2,29.8,29.5,24.5,100.0,100.0,26.9
4,V00000005,L00000005,S00000005,D00000005,Honda,Accord,Accord GT,2022,2022,4,...,23.1,42.5,17.4,78.0,22.5,0.0,10.4,74.7,74.6,36.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,V00099996,L00099996,S00004996,D00001996,Volkswagen,Jetta,Jetta SEL,2020,2020,6,...,19.4,39.4,58.9,66.5,41.2,22.8,15.3,79.3,65.3,37.9
99996,V00099997,L00099997,S00004997,NaN,Ford,Transit,Transit Premium,2026,2026,0,...,40.3,64.6,40.6,65.1,37.7,2.5,1.9,23.6,29.9,51.5
99997,V00099998,L00099998,S00004998,D00001998,Chevrolet,Traverse,Traverse Limited,2026,2026,0,...,35.7,48.2,33.4,67.3,35.1,17.4,5.3,1.3,10.1,37.6
99998,V00099999,L00099999,S00004999,D00001999,Mazda,Mazda6,Mazda6 Base,2023,2023,3,...,27.6,45.6,44.0,74.9,18.5,20.0,13.3,33.0,45.8,36.8
99999,V00100000,L00100000,S00005000,NaN,Hyundai,Ioniq,Ioniq M Sport,2020,2020,6,...,57.0,60.4,79.8,56.3,39.1,25.4,0.0,56.4,74.4,24.6